// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmm2CCAWVV3cnmFOf8hl7JbgcbTGnmOxs',
    appId: '1:966972100840:web:a653a32a8390a7ef90395d',
    messagingSenderId: '966972100840',
    projectId: 'session36-d9d73',
    authDomain: 'session36-d9d73.firebaseapp.com',
    storageBucket: 'session36-d9d73.firebasestorage.app',
    measurementId: 'G-3GPLRYKWMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmK1rqbZcVxpk0P6HvMkkhNm-3P_l5cME',
    appId: '1:966972100840:android:b7a4cced465d4bff90395d',
    messagingSenderId: '966972100840',
    projectId: 'session36-d9d73',
    storageBucket: 'session36-d9d73.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhSyqqqxe4g-17o9iEJQvRJyv4wcIAFeU',
    appId: '1:966972100840:ios:ec099c17736e903090395d',
    messagingSenderId: '966972100840',
    projectId: 'session36-d9d73',
    storageBucket: 'session36-d9d73.firebasestorage.app',
    iosBundleId: 'com.example.exerciseProjects',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhSyqqqxe4g-17o9iEJQvRJyv4wcIAFeU',
    appId: '1:966972100840:ios:ec099c17736e903090395d',
    messagingSenderId: '966972100840',
    projectId: 'session36-d9d73',
    storageBucket: 'session36-d9d73.firebasestorage.app',
    iosBundleId: 'com.example.exerciseProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmm2CCAWVV3cnmFOf8hl7JbgcbTGnmOxs',
    appId: '1:966972100840:web:0c07aaa27fc222d390395d',
    messagingSenderId: '966972100840',
    projectId: 'session36-d9d73',
    authDomain: 'session36-d9d73.firebaseapp.com',
    storageBucket: 'session36-d9d73.firebasestorage.app',
    measurementId: 'G-GFY4L26J3D',
  );
}
